name: build-exe

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:

    - name: checkout
      uses: actions/checkout@v4

    - name: python setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: install dependencies
      run: |
        pip install -r requirements.txt
        pip install pyinstaller

    - name: build exe
      run: |
        pyinstaller --onefile --windowed main.py

    - name: upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: excel-auto-input
        path: dist/main.exe
